export interface SeedGame {
  title: string;
  description: string;
  coverImage: string;
  releaseDate: string;
  status: "upcoming" | "released";
  genre: string;
  developer: string;
  publisher: string;
  platform: string;
  featured: boolean;
  rating: string;
  storeLinks: { name: string; url: string; icon?: string }[];
  order: number;
}

export const seedGames: SeedGame[] = [
  {
    title: "Grand Theft Auto VI",
    description: "The most anticipated game of the decade. Return to the state of Leonida in this sprawling open-world adventure featuring Lucia and Jason in a story of crime, ambition, and the pursuit of the American Dream.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1546990/header.jpg",
    releaseDate: "2026-05-26",
    status: "upcoming",
    genre: "Action-Adventure / Open World",
    developer: "Rockstar North",
    publisher: "Rockstar Games",
    platform: "PS5, Xbox Series X/S",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 1,
  },
  {
    title: "The Elder Scrolls VI",
    description: "Bethesda's long-awaited return to the Elder Scrolls universe. Explore a vast new province in the most ambitious RPG ever created.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1643320/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "RPG / Open World",
    developer: "Bethesda Game Studios",
    publisher: "Bethesda Softworks",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 2,
  },
  {
    title: "Ghost of Yōtei",
    description: "Sucker Punch's follow-up to Ghost of Tsushima. Journey to Hokkaido in 1603 as a new warrior faces supernatural threats in a stunning open world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2906030/header.jpg",
    releaseDate: "2025-10-02",
    status: "upcoming",
    genre: "Action-Adventure / Open World",
    developer: "Sucker Punch Productions",
    publisher: "Sony Interactive Entertainment",
    platform: "PS5",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 3,
  },
  {
    title: "Marvel's Wolverine",
    description: "Experience the brutal journey of Logan in an original story set in the Marvel universe. Developed by Insomniac Games, creators of Spider-Man.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2252570/header.jpg",
    releaseDate: "2026-03-15",
    status: "upcoming",
    genre: "Action-Adventure",
    developer: "Insomniac Games",
    publisher: "Sony Interactive Entertainment",
    platform: "PS5",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 4,
  },
  {
    title: "Fable",
    description: "The beloved RPG franchise returns with a new vision from Playground Games. Explore the magical world of Albion in a stunning open-world adventure.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2769570/header.jpg",
    releaseDate: "2026-08-12",
    status: "upcoming",
    genre: "RPG / Action",
    developer: "Playground Games",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: true,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 5,
  },
  {
    title: "Death Stranding 2: On The Beach",
    description: "Hideo Kojima's sequel to the genre-defying original. Sam Porter Bridges embarks on a new journey that will test the bonds of humanity.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1190460/header.jpg",
    releaseDate: "2025-06-26",
    status: "released",
    genre: "Action / Adventure",
    developer: "Kojima Productions",
    publisher: "Sony Interactive Entertainment",
    platform: "PS5",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 6,
  },
  {
    title: "Monster Hunter Wilds",
    description: "Capcom's next evolution of the Monster Hunter franchise. Hunt in a dynamic, living ecosystem with seamless open-world exploration.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2246340/header.jpg",
    releaseDate: "2025-02-28",
    status: "released",
    genre: "Action RPG",
    developer: "Capcom",
    publisher: "Capcom",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 7,
  },
  {
    title: "Assassin's Creed Shadows",
    description: "Journey to feudal Japan in the latest Assassin's Creed. Play as Naoe, a shinobi, and Yasuke, a samurai, in a breathtaking open world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3159330/header.jpg",
    releaseDate: "2025-03-20",
    status: "released",
    genre: "Action-Adventure / RPG",
    developer: "Ubisoft Quebec",
    publisher: "Ubisoft",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Ubisoft Store", url: "https://store.ubi.com", icon: "ubisoft" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 8,
  },
  {
    title: "Doom: The Dark Ages",
    description: "The Slayer's origins revealed. Travel to a medieval-inspired world and unleash devastating new weapons against the forces of Hell.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3017860/header.jpg",
    releaseDate: "2025-05-15",
    status: "released",
    genre: "FPS / Action",
    developer: "id Software",
    publisher: "Bethesda Softworks",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 9,
  },
  {
    title: "Clair Obscur: Expedition 33",
    description: "A stunning turn-based RPG set in a Belle Époque-inspired fantasy world. Lead Expedition 33 to destroy the Paintress before she paints death again.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1903340/header.jpg",
    releaseDate: "2025-04-24",
    status: "released",
    genre: "Turn-Based RPG",
    developer: "Sandfall Interactive",
    publisher: "Kepler Interactive",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 10,
  },
  {
    title: "Hollow Knight: Silksong",
    description: "The long-awaited sequel to Hollow Knight. Play as Hornet and explore a vast new kingdom filled with mystery and danger.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1030300/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Metroidvania / Action",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    platform: "PC, PS5, Xbox Series X/S, Switch",
    featured: true,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Nintendo eShop", url: "https://www.nintendo.com", icon: "nintendo" },
    ],
    order: 11,
  },
  {
    title: "Intergalactic: The Heretic Prophet",
    description: "Naughty Dog's new IP. A sci-fi adventure set in a distant galaxy where a bounty hunter is stranded on a mysterious planet.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2923630/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "Action-Adventure / Sci-Fi",
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    platform: "PS5",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 12,
  },
  {
    title: "Mafia: The Old Country",
    description: "Return to the roots of organized crime in this prequel set in 1900s Sicily. A story of family, honor, and betrayal.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1941540/header.jpg",
    releaseDate: "2025-08-08",
    status: "upcoming",
    genre: "Action-Adventure",
    developer: "Hangar 13",
    publisher: "2K Games",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 13,
  },
  {
    title: "Wuchang: Fallen Feathers",
    description: "A souls-like action RPG set in the dark and mysterious world of Chinese mythology during the Ming Dynasty.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2277560/header.jpg",
    releaseDate: "2025-07-10",
    status: "upcoming",
    genre: "Action RPG / Souls-like",
    developer: "Leenzee Games",
    publisher: "505 Games",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 14,
  },
  {
    title: "Sid Meier's Civilization VII",
    description: "The next chapter in the legendary strategy franchise. Build your empire through the ages with revolutionary new gameplay systems.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1295660/header.jpg",
    releaseDate: "2025-02-11",
    status: "released",
    genre: "Strategy / 4X",
    developer: "Firaxis Games",
    publisher: "2K Games",
    platform: "PC, PS5, Xbox Series X/S, Switch",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 15,
  },
  {
    title: "Avowed",
    description: "Obsidian Entertainment's first-person RPG set in the Living Lands of Eora. Uncover ancient mysteries and shape the fate of the world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2457220/header.jpg",
    releaseDate: "2025-02-18",
    status: "released",
    genre: "RPG / First-Person",
    developer: "Obsidian Entertainment",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 16,
  },
  {
    title: "Kingdom Come: Deliverance II",
    description: "Henry's story continues in this authentic medieval RPG. Experience 15th century Bohemia with unprecedented realism.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1771300/header.jpg",
    releaseDate: "2025-02-04",
    status: "released",
    genre: "RPG / Open World",
    developer: "Warhorse Studios",
    publisher: "Deep Silver",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 17,
  },
  {
    title: "Like a Dragon: Pirate Yakuza in Hawaii",
    description: "Goro Majima gets his own adventure! Set sail on the high seas as the Mad Dog of Shimano in this wild spinoff.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3061810/header.jpg",
    releaseDate: "2025-02-21",
    status: "released",
    genre: "Action-Adventure / RPG",
    developer: "Ryu Ga Gotoku Studio",
    publisher: "SEGA",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 18,
  },
  {
    title: "Split Fiction",
    description: "From the creators of It Takes Two comes a new co-op adventure that blends sci-fi and fantasy in unexpected ways.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2001120/header.jpg",
    releaseDate: "2025-03-06",
    status: "released",
    genre: "Co-op / Adventure",
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "EA Store", url: "https://www.ea.com", icon: "ea" },
    ],
    order: 19,
  },
  {
    title: "South of Midnight",
    description: "From Compulsion Games, explore the deep South's folklore in this atmospheric action-adventure with stunning art direction.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1392860/header.jpg",
    releaseDate: "2025-04-08",
    status: "released",
    genre: "Action-Adventure",
    developer: "Compulsion Games",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 20,
  },
  {
    title: "Little Nightmares III",
    description: "The nightmarish adventure continues. Navigate a world of terrifying wonders with a friend in this co-op horror platformer.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2131650/header.jpg",
    releaseDate: "2025-10-10",
    status: "upcoming",
    genre: "Horror / Platformer",
    developer: "Supermassive Games",
    publisher: "Bandai Namco",
    platform: "PC, PS5, Xbox Series X/S, Switch",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 21,
  },
  {
    title: "Metal Gear Solid Δ: Snake Eater",
    description: "The beloved classic returns with stunning Unreal Engine 5 graphics. Relive Big Boss's origin story like never before.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2252570/header.jpg",
    releaseDate: "2025-08-28",
    status: "upcoming",
    genre: "Action / Stealth",
    developer: "Virtuos",
    publisher: "Konami",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 22,
  },
  {
    title: "Clockwork Revolution",
    description: "inXile's steampunk RPG. Manipulate time in a Victorian-inspired world where technology and magic collide.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2439280/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "RPG / Steampunk",
    developer: "inXile Entertainment",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 23,
  },
  {
    title: "The Outer Worlds 2",
    description: "The sequel to Obsidian's acclaimed sci-fi RPG. Explore a new star system with even more choices, consequences, and dark humor.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1449110/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "RPG / Sci-Fi",
    developer: "Obsidian Entertainment",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S, PS5",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 24,
  },
  {
    title: "Perfect Dark",
    description: "The classic franchise reimagined by The Initiative. Step into the shoes of Agent Dark in a near-future espionage thriller.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2677660/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "FPS / Espionage",
    developer: "The Initiative",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 25,
  },
  {
    title: "State of Decay 3",
    description: "Survive the zombie apocalypse in Undead Labs' ambitious sequel. Build your community, manage resources, and fight for survival.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1340720/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Survival / Action",
    developer: "Undead Labs",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 26,
  },
  {
    title: "Everwild",
    description: "Rare's magical new IP. Explore a breathtaking natural world and forge connections with mysterious creatures.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2416760/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Adventure / Exploration",
    developer: "Rare",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 27,
  },
  {
    title: "Judas",
    description: "Ken Levine's Ghost Story game. A narrative-driven FPS set on a dying starship with revolutionary storytelling.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1941540/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "FPS / Narrative",
    developer: "Ghost Story Games",
    publisher: "Take-Two Interactive",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 28,
  },
  {
    title: "Contraband",
    description: "Avalanche Studios' 1970s smuggling co-op game set in a fictional world inspired by the Bayou.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1400770/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action / Co-op",
    developer: "Avalanche Studios",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 29,
  },
  {
    title: "Indiana Jones and the Great Circle",
    description: "MachineGames' Indiana Jones adventure. Uncover the mystery of the Great Circle in this authentic Indy experience.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2729560/header.jpg",
    releaseDate: "2024-12-09",
    status: "released",
    genre: "Action-Adventure",
    developer: "MachineGames",
    publisher: "Bethesda Softworks",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 30,
  },
  {
    title: "The Legend of Zelda: Echoes of Wisdom",
    description: "Play as Princess Zelda for the first time in a mainline Zelda game. Save Hyrule using the power of echoes.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1030300/header.jpg",
    releaseDate: "2024-09-26",
    status: "released",
    genre: "Action-Adventure / Puzzle",
    developer: "Nintendo",
    publisher: "Nintendo",
    platform: "Switch",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Nintendo eShop", url: "https://www.nintendo.com", icon: "nintendo" },
    ],
    order: 31,
  },
  {
    title: "Elden Ring: Nightreign",
    description: "A standalone adventure in the Elden Ring universe. Face the Night Lord in this cooperative roguelike experience.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3017860/header.jpg",
    releaseDate: "2025-06-11",
    status: "released",
    genre: "Action RPG / Roguelike",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 32,
  },
  {
    title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    description: "The long-awaited sequel to the cult classic. Explore the Chornobyl Exclusion Zone in this atmospheric FPS.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1643320/header.jpg",
    releaseDate: "2024-11-20",
    status: "released",
    genre: "FPS / Survival",
    developer: "GSC Game World",
    publisher: "GSC Game World",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 33,
  },
  {
    title: "Dragon Age: The Veilguard",
    description: "BioWare's return to Thedas. Assemble your team and face the return of the elven gods in this epic RPG.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2769570/header.jpg",
    releaseDate: "2024-10-31",
    status: "released",
    genre: "RPG / Action",
    developer: "BioWare",
    publisher: "Electronic Arts",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "EA Store", url: "https://www.ea.com", icon: "ea" },
    ],
    order: 34,
  },
  {
    title: "Silent Hill 2 Remake",
    description: "Bloober Team's reimagining of the horror classic. James Sunderland returns to Silent Hill in stunning detail.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2131650/header.jpg",
    releaseDate: "2024-10-08",
    status: "released",
    genre: "Survival Horror",
    developer: "Bloober Team",
    publisher: "Konami",
    platform: "PC, PS5",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 35,
  },
  {
    title: "Black Myth: Wukong",
    description: "Game Science's action RPG based on Chinese mythology. Become the Destined One and face legendary challenges.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2277560/header.jpg",
    releaseDate: "2024-08-20",
    status: "released",
    genre: "Action RPG",
    developer: "Game Science",
    publisher: "Game Science",
    platform: "PC, PS5",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 36,
  },
  {
    title: "Astro Bot",
    description: "Team Asobi's delightful 3D platformer. Explore creative worlds in this PS5 exclusive that celebrates PlayStation history.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1903340/header.jpg",
    releaseDate: "2024-09-06",
    status: "released",
    genre: "3D Platformer",
    developer: "Team Asobi",
    publisher: "Sony Interactive Entertainment",
    platform: "PS5",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 37,
  },
  {
    title: "Metroid Prime 4: Beyond",
    description: "Samus Aran returns in the long-awaited fourth installment of the Metroid Prime series. A new adventure awaits.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2923630/header.jpg",
    releaseDate: "2025-09-19",
    status: "upcoming",
    genre: "FPS / Action-Adventure",
    developer: "Retro Studios",
    publisher: "Nintendo",
    platform: "Switch",
    featured: true,
    rating: "T",
    storeLinks: [
      { name: "Nintendo eShop", url: "https://www.nintendo.com", icon: "nintendo" },
    ],
    order: 38,
  },
  {
    title: "Pokémon Legends: Z-A",
    description: "Return to the Kalos region in this sequel to Pokémon Legends: Arceus. Explore Lumiose City in a new way.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1030300/header.jpg",
    releaseDate: "2025-10-16",
    status: "upcoming",
    genre: "RPG / Action",
    developer: "Game Freak",
    publisher: "Nintendo",
    platform: "Switch",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Nintendo eShop", url: "https://www.nintendo.com", icon: "nintendo" },
    ],
    order: 39,
  },
  {
    title: "Project: Mara",
    description: "Ninja Theory's experimental horror game exploring the nature of mental health through a single setting.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2131650/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Horror / Narrative",
    developer: "Ninja Theory",
    publisher: "Xbox Game Studios",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 40,
  },
  {
    title: "Warhammer 40,000: Space Marine 2",
    description: "The sequel to the beloved third-person shooter. Defend the Imperium as Lieutenant Titus against the Tyranid swarm.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3017860/header.jpg",
    releaseDate: "2024-09-09",
    status: "released",
    genre: "Third-Person Shooter",
    developer: "Saber Interactive",
    publisher: "Focus Entertainment",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 41,
  },
  {
    title: "Star Wars Outlaws",
    description: "Ubisoft's open-world Star Wars game. Play as scoundrel Kay Vess in the galaxy's underworld.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1449110/header.jpg",
    releaseDate: "2024-08-30",
    status: "released",
    genre: "Action-Adventure / Open World",
    developer: "Massive Entertainment",
    publisher: "Ubisoft",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Ubisoft Store", url: "https://store.ubi.com", icon: "ubisoft" },
    ],
    order: 42,
  },
  {
    title: "Helldivers 2",
    description: "Arrowhead's hit cooperative shooter. Spread democracy across the galaxy in this intense third-person action game.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2246340/header.jpg",
    releaseDate: "2024-02-08",
    status: "released",
    genre: "Third-Person Shooter / Co-op",
    developer: "Arrowhead Game Studios",
    publisher: "Sony Interactive Entertainment",
    platform: "PC, PS5",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 43,
  },
  {
    title: "Final Fantasy VII Rebirth",
    description: "The second chapter of the FF7 Remake project. Cloud and friends venture beyond Midgar into a vast open world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2001120/header.jpg",
    releaseDate: "2024-02-29",
    status: "released",
    genre: "RPG / Action",
    developer: "Square Enix",
    publisher: "Square Enix",
    platform: "PS5, PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 44,
  },
  {
    title: "Tekken 8",
    description: "The King of Iron Fist Tournament continues with stunning visuals and refined gameplay in Bandai Namco's premier fighter.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1546990/header.jpg",
    releaseDate: "2024-01-26",
    status: "released",
    genre: "Fighting",
    developer: "Bandai Namco",
    publisher: "Bandai Namco",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 45,
  },
  {
    title: "Like a Dragon: Infinite Wealth",
    description: "Ichiban Kasuga and Kazuma Kiryu's stories intertwine in this massive RPG spanning Japan and Hawaii.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3061810/header.jpg",
    releaseDate: "2024-01-26",
    status: "released",
    genre: "RPG / Turn-Based",
    developer: "Ryu Ga Gotoku Studio",
    publisher: "SEGA",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 46,
  },
  {
    title: "Balatro",
    description: "The roguelike deck builder that took the world by storm. Build insane poker hands and break the game.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1392860/header.jpg",
    releaseDate: "2024-02-20",
    status: "released",
    genre: "Roguelike / Card Game",
    developer: "LocalThunk",
    publisher: "Playstack",
    platform: "PC, PS5, Xbox, Switch, Mobile",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 47,
  },
  {
    title: "Hades II",
    description: "Supergiant's sequel to the beloved roguelike. Play as Melinoë and battle through the underworld to defeat Chronos.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2769570/header.jpg",
    releaseDate: "2024-05-06",
    status: "released",
    genre: "Roguelike / Action",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    platform: "PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 48,
  },
  {
    title: "Pacific Drive",
    description: "A survival driving game set in the Olympic Exclusion Zone. Your car is your only companion in this anomalous wasteland.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1400770/header.jpg",
    releaseDate: "2024-02-22",
    status: "released",
    genre: "Survival / Driving",
    developer: "Ironwood Studios",
    publisher: "Kepler Interactive",
    platform: "PC, PS5",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 49,
  },
  {
    title: "Prince of Persia: The Lost Crown",
    description: "A return to 2D action-platforming in the Prince of Persia franchise with Metroidvania elements and stunning combat.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1771300/header.jpg",
    releaseDate: "2024-01-18",
    status: "released",
    genre: "Action-Platformer / Metroidvania",
    developer: "Ubisoft Montpellier",
    publisher: "Ubisoft",
    platform: "PC, PS5, Xbox Series X/S, Switch",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Ubisoft Store", url: "https://store.ubi.com", icon: "ubisoft" },
    ],
    order: 50,
  },
  {
    title: "Den of Wolves",
    description: "10 Chambers' cooperative heist game set in a futuristic sci-fi world. Plan and execute daring operations.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2677660/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "FPS / Co-op / Heist",
    developer: "10 Chambers",
    publisher: "10 Chambers",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 51,
  },
  {
    title: "Ninja Gaiden 4",
    description: "The legendary action franchise returns with a new entry. Face impossible odds with lightning-fast combat.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2906030/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action / Hack & Slash",
    developer: "Team Ninja",
    publisher: "Koei Tecmo",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 52,
  },
  {
    title: "Dispatch",
    description: "A narrative-driven superhero management game where you run a hero dispatch center. From the creators of Firewatch.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2439280/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Narrative / Management",
    developer: "Campo Santo",
    publisher: "Valve",
    platform: "PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 53,
  },
  {
    title: "Blight: Survival",
    description: "A cooperative survival horror game set in a medieval world plagued by a mysterious blight.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2131650/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Survival Horror / Co-op",
    developer: "Häven Interactive",
    publisher: "Häven Interactive",
    platform: "PC",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 54,
  },
  {
    title: "Neva",
    description: "Devolver Digital's emotional action-adventure about a woman and her wolf companion navigating a dark world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2416760/header.jpg",
    releaseDate: "2024-10-15",
    status: "released",
    genre: "Action-Adventure / Platformer",
    developer: "Replika Studios",
    publisher: "Devolver Digital",
    platform: "PC, PS5, Xbox Series X/S, Switch",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 55,
  },
  {
    title: "Unrecord",
    description: "A bodycam-style FPS with hyper-realistic visuals. Experience a detective's journey through the criminal underworld.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1941540/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "FPS / Narrative",
    developer: "Drama",
    publisher: "Drama",
    platform: "PC",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 56,
  },
  {
    title: "Crimson Desert",
    description: "Pearl Abyss's ambitious open-world action-adventure. Follow Kliff's journey in the war-torn continent of Pywel.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1771300/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action-Adventure / Open World",
    developer: "Pearl Abyss",
    publisher: "Pearl Abyss",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 57,
  },
  {
    title: "Where Winds Meet",
    description: "An open-world action RPG set in ancient China during the Ten Kingdoms period. Martial arts and destiny collide.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2277560/header.jpg",
    releaseDate: "2025-12-18",
    status: "upcoming",
    genre: "Action RPG / Open World",
    developer: "Everstone Studio",
    publisher: "NetEase",
    platform: "PC, PS5",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 58,
  },
  {
    title: "Vigilant",
    description: "An atmospheric horror game inspired by Lovecraftian mythology. Uncover the secrets of a cursed lighthouse.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2457220/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Horror / Adventure",
    developer: "Red Hook Studios",
    publisher: "Red Hook Studios",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 59,
  },
  {
    title: "Tides of Annihilation",
    description: "A fantasy action RPG set in a world being consumed by an otherworldly fog. Inspired by Arthurian legends.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1190460/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action RPG / Fantasy",
    developer: "Ebb Software",
    publisher: "Ebb Software",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 60,
  },
  {
    title: "Dual Deaths",
    description: "A unique co-op puzzle game where two players must navigate parallel dimensions to solve mysteries.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2001120/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Puzzle / Co-op",
    developer: "Hazelight Studios",
    publisher: "Electronic Arts",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 61,
  },
  {
    title: "Onimusha: Way of the Sword",
    description: "Capcom revives the Onimusha franchise with a brand new action game set in feudal Japan with supernatural elements.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2906030/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action / Hack & Slash",
    developer: "Capcom",
    publisher: "Capcom",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 62,
  },
  {
    title: "Rennsport",
    description: "A realistic racing simulator built for competitive esports. Featuring laser-scanned tracks and authentic driving physics.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1400770/header.jpg",
    releaseDate: "2025-11-15",
    status: "upcoming",
    genre: "Racing / Simulation",
    developer: "Competition Company",
    publisher: "Competition Company",
    platform: "PC, PS5",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 63,
  },
  {
    title: "Cairn",
    description: "A survival climbing game where you must ascend a treacherous mountain. Every decision could be your last.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2416760/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Survival / Adventure",
    developer: "The Game Bakers",
    publisher: "The Game Bakers",
    platform: "PC, PS5, Switch",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 64,
  },
  {
    title: "Routine",
    description: "A retro-futuristic horror game set on an abandoned moon base. Discover what happened to the crew in this terrifying FPS.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2923630/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Horror / FPS",
    developer: "Lunar Software",
    publisher: "Raw Fury",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 65,
  },
  {
    title: "The Last of Us Part III",
    description: "Naughty Dog's potential conclusion to the acclaimed series. Ellie's story may continue in this highly anticipated sequel.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2457220/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "Action-Adventure / Survival",
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    platform: "PS5",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 66,
  },
  {
    title: "God of War: Next Chapter",
    description: "The next installment in Kratos's saga. Where will the God of War's journey take him next?",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3017860/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "Action-Adventure",
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    platform: "PS5",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 67,
  },
  {
    title: "Horizon Online",
    description: "Guerilla Games' multiplayer foray into the Horizon universe. Explore the post-apocalyptic world with friends.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2416760/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action RPG / MMO",
    developer: "Guerrilla Games",
    publisher: "Sony Interactive Entertainment",
    platform: "PS5, PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "PlayStation Store", url: "https://store.playstation.com", icon: "playstation" },
    ],
    order: 68,
  },
  {
    title: "Asgard's Wrath 2",
    description: "The VR epic comes to flat screens. Battle Norse and Egyptian gods in this massive action RPG.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2769570/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action RPG",
    developer: "Sanzaru Games",
    publisher: "Meta",
    platform: "PC, PS5",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 69,
  },
  {
    title: "2XKO",
    description: "Riot Games' 2v2 fighting game featuring League of Legends champions. Fast-paced team-based combat.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1546990/header.jpg",
    releaseDate: "2025-08-20",
    status: "upcoming",
    genre: "Fighting / 2v2",
    developer: "Riot Games",
    publisher: "Riot Games",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 70,
  },
  {
    title: "Vampire: The Masquerade - Bloodlines 2",
    description: "The long-awaited sequel to the cult classic RPG. Navigate the treacherous politics of Seattle's vampire society.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2131650/header.jpg",
    releaseDate: "2025-10-01",
    status: "upcoming",
    genre: "RPG / Vampire",
    developer: "The Chinese Room",
    publisher: "Paradox Interactive",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "GOG", url: "https://www.gog.com", icon: "gog" },
    ],
    order: 71,
  },
  {
    title: "Spectre Divide",
    description: "A unique tactical shooter where you control two bodies simultaneously. Outsmart opponents with dual-perspective gameplay.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2246340/header.jpg",
    releaseDate: "2025-12-05",
    status: "upcoming",
    genre: "FPS / Tactical",
    developer: "Mountaintop Studios",
    publisher: "Mountaintop Studios",
    platform: "PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 72,
  },
  {
    title: "Towers of Aghasba",
    description: "An open-world fantasy building game. Restore a barren island to its former glory and build a thriving civilization.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1392860/header.jpg",
    releaseDate: "2025-11-20",
    status: "upcoming",
    genre: "Building / Open World",
    developer: "Dreams of Immortality",
    publisher: "Dreams of Immortality",
    platform: "PC, PS5",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 73,
  },
  {
    title: "No Rest for the Wicked",
    description: "Moon Studios' ambitious action RPG with precise combat and a dark, painterly art style.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1903340/header.jpg",
    releaseDate: "2025-09-15",
    status: "upcoming",
    genre: "Action RPG",
    developer: "Moon Studios",
    publisher: "Private Division",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 74,
  },
  {
    title: "MudRunner 2",
    description: "The ultimate off-road driving experience returns with more vehicles, maps, and extreme conditions.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1400770/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Simulation / Driving",
    developer: "Saber Interactive",
    publisher: "Focus Entertainment",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 75,
  },
  {
    title: "ArcheAge Chronicles",
    description: "A new MMORPG in the ArcheAge universe. Explore vast seas and continents in this sandbox online world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1190460/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "MMORPG",
    developer: "XLGAMES",
    publisher: "Kakao Games",
    platform: "PC, PS5",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 76,
  },
  {
    title: "Wildgate",
    description: "A sci-fi FPS with procedural generation. Explore the galaxy, fight aliens, and uncover ancient secrets.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1449110/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "FPS / Sci-Fi",
    developer: "Wildcard Games",
    publisher: "Wildcard Games",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 77,
  },
  {
    title: "The Witcher 4",
    description: "CD Projekt Red's next Witcher game. A new saga begins with Ciri as the protagonist in a dark fantasy world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2769570/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "RPG / Open World",
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "GOG", url: "https://www.gog.com", icon: "gog" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 78,
  },
  {
    title: "Project: M",
    description: "A mysterious new fighting game from a legendary developer. Details remain scarce but anticipation is high.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1546990/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Fighting",
    developer: "Bandai Namco",
    publisher: "Bandai Namco",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 79,
  },
  {
    title: "Project 007",
    description: "IO Interactive's original James Bond game. Experience the origin story of 007 in this spy thriller.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2677660/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action / Stealth",
    developer: "IO Interactive",
    publisher: "IO Interactive",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 80,
  },
  {
    title: "Behind the Frame: Finest Express",
    description: "A beautiful narrative puzzle game about an artist's journey on a luxury train. Paint your way through a mystery.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1392860/header.jpg",
    releaseDate: "2025-12-01",
    status: "upcoming",
    genre: "Puzzle / Narrative",
    developer: "Silver Lining Studio",
    publisher: "Akupara Games",
    platform: "PC, Switch, Mobile",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Nintendo eShop", url: "https://www.nintendo.com", icon: "nintendo" },
    ],
    order: 81,
  },
  {
    title: "Durandal",
    description: "An isometric action RPG set in a dark fantasy world inspired by medieval European mythology.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1771300/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action RPG / Isometric",
    developer: "Shift Up",
    publisher: "Shift Up",
    platform: "PC, PS5",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 82,
  },
  {
    title: "Archetype Entertainment's New RPG",
    description: "A brand new RPG from Archetype Entertainment, featuring a rich sci-fi universe with deep choice-driven narrative.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1449110/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "RPG / Sci-Fi",
    developer: "Archetype Entertainment",
    publisher: "Wizards of the Coast",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 83,
  },
  {
    title: "Titan Quest 2",
    description: "The mythological action RPG returns. Battle through ancient Greek, Egyptian, and Norse mythology in a new epic adventure.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2769570/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Action RPG / Mythology",
    developer: "Grimlore Games",
    publisher: "THQ Nordic",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 84,
  },
  {
    title: "Gothic Remake",
    description: "THQ Nordic's complete reimagining of the classic Gothic RPG. Return to the mining colony with modern visuals and gameplay.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2457220/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "RPG / Open World",
    developer: "Alkimia Interactive",
    publisher: "THQ Nordic",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "GOG", url: "https://www.gog.com", icon: "gog" },
    ],
    order: 85,
  },
  {
    title: "Mighty Morphin Power Rangers: Rita's Rewind",
    description: "A retro-inspired beat 'em up featuring the original Power Rangers. Fight Putties and iconic villains.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1030300/header.jpg",
    releaseDate: "2025-12-10",
    status: "upcoming",
    genre: "Beat 'em Up / Retro",
    developer: "Digital Eclipse",
    publisher: "Hasbro",
    platform: "PC, PS5, Xbox, Switch",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 86,
  },
  {
    title: "Light No Fire",
    description: "Hello Games' ambitious new project. Explore a fantasy planet with friends in this procedural open-world adventure.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2416760/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Adventure / Open World / Co-op",
    developer: "Hello Games",
    publisher: "Hello Games",
    platform: "PC, PS5, Xbox Series X/S",
    featured: true,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 87,
  },
  {
    title: "Road 96: Mile 0",
    description: "The prequel to the hit procedural narrative game. Discover what happened before the road trip began.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1400770/header.jpg",
    releaseDate: "2026",
    status: "upcoming",
    genre: "Adventure / Narrative",
    developer: "DigixArt",
    publisher: "DigixArt",
    platform: "PC, PS5, Xbox Series X/S, Switch",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 88,
  },
  {
    title: "Replaced",
    description: "A cinematic platformer set in an alternate 1980s America. Play as an AI trapped in a human body.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2439280/header.jpg",
    releaseDate: "2025-11-25",
    status: "upcoming",
    genre: "Platformer / Cinematic",
    developer: "Sad Cat Studios",
    publisher: "Coatsink",
    platform: "PC, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Xbox Store", url: "https://www.xbox.com", icon: "xbox" },
    ],
    order: 89,
  },
  {
    title: "Stormgate",
    description: "Frost Giant Studios' new RTS from former Blizzard developers. Command armies in a sci-fi/fantasy conflict.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1295660/header.jpg",
    releaseDate: "2025-08-15",
    status: "upcoming",
    genre: "RTS / Strategy",
    developer: "Frost Giant Studios",
    publisher: "Frost Giant Studios",
    platform: "PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 90,
  },
  {
    title: "Homeworld 3",
    description: "The legendary space RTS returns. Command your fleet in 3D space battles of unprecedented scale.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2923630/header.jpg",
    releaseDate: "2024-05-13",
    status: "released",
    genre: "RTS / Space",
    developer: "Blackbird Interactive",
    publisher: "Gearbox Publishing",
    platform: "PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 91,
  },
  {
    title: "Crow Country",
    description: "A PS1-style survival horror game set in an abandoned theme park. Uncover dark secrets and survive the night.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2131650/header.jpg",
    releaseDate: "2024-05-09",
    status: "released",
    genre: "Survival Horror / Retro",
    developer: "SFB Games",
    publisher: "SFB Games",
    platform: "PC, PS5, Switch",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 92,
  },
  {
    title: "1000xRESIST",
    description: "A mind-bending narrative adventure about cloning, memory, and resistance. A critically acclaimed indie gem.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2001120/header.jpg",
    releaseDate: "2024-06-13",
    status: "released",
    genre: "Adventure / Narrative",
    developer: "Sunset Visitor",
    publisher: "Sunset Visitor",
    platform: "PC, Switch, PS5",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 93,
  },
  {
    title: "Animal Well",
    description: "A puzzle-platformer that hides deeper mysteries beneath its charming surface. Explore a surreal underground world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1903340/header.jpg",
    releaseDate: "2024-05-09",
    status: "released",
    genre: "Puzzle-Platformer",
    developer: "Shared Memory",
    publisher: "Bigmode",
    platform: "PC, PS5, Switch",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 94,
  },
  {
    title: "Lorelei and the Laser Eyes",
    description: "An atmospheric puzzle game set in a mysterious hotel. Unravel a complex web of riddles and illusions.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2439280/header.jpg",
    releaseDate: "2024-05-16",
    status: "released",
    genre: "Puzzle / Mystery",
    developer: "Simogo",
    publisher: "Annapurna Interactive",
    platform: "PC, Switch",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 95,
  },
  {
    title: "Tactical Breach Wizards",
    description: "A turn-based tactics game where you command a team of spellcasting SWAT officers. Creative and hilarious.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2246340/header.jpg",
    releaseDate: "2024-09-11",
    status: "released",
    genre: "Turn-Based Tactics",
    developer: "Suspicious Developments",
    publisher: "Suspicious Developments",
    platform: "PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 96,
  },
  {
    title: "Frostpunk 2",
    description: "The sequel to the acclaimed city-building survival game. Lead your city through a new age of oil and conflict.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1190460/header.jpg",
    releaseDate: "2024-09-20",
    status: "released",
    genre: "City Builder / Survival",
    developer: "11 bit studios",
    publisher: "11 bit studios",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 97,
  },
  {
    title: "Satisfactory 1.0",
    description: "The factory building game reaches its full release. Build massive automated production lines on an alien planet.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1295660/header.jpg",
    releaseDate: "2024-09-10",
    status: "released",
    genre: "Factory Building / Simulation",
    developer: "Coffee Stain Studios",
    publisher: "Coffee Stain Publishing",
    platform: "PC",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 98,
  },
  {
    title: "Wuthering Waves",
    description: "Kuro Games' open-world action RPG with fast-paced combat and exploration in a post-apocalyptic world.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2277560/header.jpg",
    releaseDate: "2024-05-22",
    status: "released",
    genre: "Action RPG / Gacha",
    developer: "Kuro Games",
    publisher: "Kuro Games",
    platform: "PC, Mobile, PS5",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 99,
  },
  {
    title: "Zenless Zone Zero",
    description: "miHoYo's urban fantasy action RPG. Explore Hollows and battle Ethereals in this stylish free-to-play game.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2252570/header.jpg",
    releaseDate: "2024-07-04",
    status: "released",
    genre: "Action RPG / Urban Fantasy",
    developer: "miHoYo",
    publisher: "miHoYo",
    platform: "PC, Mobile, PS5",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Epic Games Store", url: "https://store.epicgames.com", icon: "epic" },
    ],
    order: 100,
  },
  {
    title: "Manor Lords",
    description: "A medieval strategy game combining city-building and tactical battles in a historically authentic setting.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1771300/header.jpg",
    releaseDate: "2024-04-26",
    status: "released",
    genre: "Strategy / City Builder",
    developer: "Slavic Magic",
    publisher: "Hooded Horse",
    platform: "PC",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "GOG", url: "https://www.gog.com", icon: "gog" },
    ],
    order: 101,
  },
  {
    title: "Ninja Gaiden 2 Black",
    description: "A remaster of the classic Ninja Gaiden 2 with enhanced graphics and performance for modern platforms.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2906030/header.jpg",
    releaseDate: "2025-06-20",
    status: "released",
    genre: "Action / Hack & Slash",
    developer: "Team Ninja",
    publisher: "Koei Tecmo",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 102,
  },
  {
    title: "Rematch",
    description: "Sloclap's multiplayer sports game. A 5v5 football game with deep mechanics from the creators of Sifu.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3061810/header.jpg",
    releaseDate: "2025-06-19",
    status: "released",
    genre: "Sports / Multiplayer",
    developer: "Sloclap",
    publisher: "Sloclap",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "E",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 103,
  },
  {
    title: "Dredge: The Iron Rig",
    description: "The expansion to the hit fishing horror game. Explore new waters and face deeper terrors in the Iron Rig DLC.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3061810/header.jpg",
    releaseDate: "2024-08-15",
    status: "released",
    genre: "Adventure / Horror",
    developer: "Black Salt Games",
    publisher: "Team17",
    platform: "PC, PS5, Xbox, Switch",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 104,
  },
  {
    title: "Diablo IV: Vessel of Hatred",
    description: "The first expansion for Diablo IV. Journey to Nahantu and face Mephisto's return with the new Spiritborn class.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/3017860/header.jpg",
    releaseDate: "2024-10-08",
    status: "released",
    genre: "Action RPG / Hack & Slash",
    developer: "Blizzard Entertainment",
    publisher: "Blizzard Entertainment",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
      { name: "Battle.net", url: "https://shop.battle.net", icon: "battlenet" },
    ],
    order: 105,
  },
  {
    title: "Sid Meier's Alpha Centauri Remake",
    description: "A potential remake of the legendary 4X strategy game. Explore and colonize an alien world in this classic reimagined.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2923630/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "Strategy / 4X",
    developer: "Firaxis Games",
    publisher: "2K Games",
    platform: "PC",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 106,
  },
  {
    title: "Civilization VII: DLC Pack",
    description: "New civilizations, leaders, and game modes coming to Civilization VII in this expansive DLC.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1295660/header.jpg",
    releaseDate: "2025-12-10",
    status: "upcoming",
    genre: "Strategy / 4X",
    developer: "Firaxis Games",
    publisher: "2K Games",
    platform: "PC, PS5, Xbox Series X/S, Switch",
    featured: false,
    rating: "E10+",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 107,
  },
  {
    title: "Supervive",
    description: "A MOBA battle royale hybrid from Theorycraft Games. Fast-paced hero shooter meets survival gameplay.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2246340/header.jpg",
    releaseDate: "2025-11-30",
    status: "upcoming",
    genre: "MOBA / Battle Royale",
    developer: "Theorycraft Games",
    publisher: "Theorycraft Games",
    platform: "PC",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 108,
  },
  {
    title: "Dungeons & Dragons: The Veil",
    description: "A new D&D video game adaptation from Hasbro. Explore the Forgotten Realms in this ambitious RPG.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/2769570/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "RPG / Fantasy",
    developer: "Hidden Path Entertainment",
    publisher: "Wizards of the Coast",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "T",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 109,
  },
  {
    title: "Prey 2",
    description: "A potential sequel to Arkane's Prey. Return to the Talos universe with new powers and threats.",
    coverImage: "https://cdn.akamai.steamstatic.com/steam/apps/1449110/header.jpg",
    releaseDate: "2027",
    status: "upcoming",
    genre: "FPS / Immersive Sim",
    developer: "Arkane Studios",
    publisher: "Bethesda Softworks",
    platform: "PC, PS5, Xbox Series X/S",
    featured: false,
    rating: "M",
    storeLinks: [
      { name: "Steam", url: "https://store.steampowered.com", icon: "steam" },
    ],
    order: 110,
  },
];
